### ISSUE TITLE
rpi camera support

### ISSUE THREAD

**Issue by mayingbin** [lineage-rpi/android_device_brcm_rpi4#3]
Hi, konstakang:
  Could you offer the modification or some suggestion to support official Pi camera modules？
  I  just config the defconfig: CONFIG_MEDIA_SUPPORT=y and CONFIG_VIDEO_BCM2835_UNICAM=y.
  I appreciate your help.

**Comment by KonstaT** [comment]
Official Pi camera modules are already supported on my builds. Details have been discussed here (https://github.com/lineage-rpi/android_local_manifest/issues/9#issuecomment-671292548).

**Comment by mayingbin** [comment]
Great, thanks very much for your help and working.

**Comment by mayingbin** [comment]
Hi, konstakang:
 use the camera.zip from lineage-rpi/android_local_manifest#9 (comment)).
  when compile camera.rpi, do you encounter VNDK link libcamera_client  error：
  **camera.rpi (native:vendor) should not link to libcamera_client (native:platform)**
  
  Do you have suggestion to solve it?

**Comment by KonstaT** [comment]
It seems you're building on platform that enables VNDK. See https://source.android.com/devices/architecture/vndk.

**Comment by mayingbin** [comment]
Yes, I solve it by Andorid.mk copy form system/lib/hw/camera.rpi.so to vendor/lib/hw/camera.rpi.so 
and modify vndk access from ld.config.txt.

**Comment by ohmex** [comment]
> Yes, I solve it by Andorid.mk copy form system/lib/hw/camera.rpi.so to vendor/lib/hw/camera.rpi.so
> and modify vndk access from ld.config.txt.

Hi could please let me know how you modified the vndk access?

**Comment by rsglobal** [comment]
You can try this: https://github.com/rsglobal/glodroid_forks/tree/hardware-libcamera
Sources and modifications was provided to me by @KonstaT , I've applied VNDK support to the code, but I have no idea will it work for you.

**Comment by ohmex** [comment]
sure will try it out

**Comment by ohmex** [comment]
I was able to compile and use the HAL, but its stopping abruptly after showing the first camera image.
Attaching the console log, please guide me how should I proceed.
[Console Logs](https://github.com/lineage-rpi/android_device_brcm_rpi4/files/5535773/Camera2_console_logs.txt)
[Logcat Logs](https://github.com/lineage-rpi/android_device_brcm_rpi4/files/5536025/logcat.txt)


PS: I am using Android-rpi code by Peter Yoon https://github.com/android-rpi/device_arpi_rpi4
Should you like suggest any other? My aim is to get official camera v1.3 with WiFi working.

**Comment by KonstaT** [comment]
@ohmex Sorry for the late reply, completely forgot about this.

There is also the same issue with the stock camera app on my LineageOS 17.1 builds for the Pi 4. Many third party camera apps seem to work. I suspect it's a gralloc issue because this works on the Pi 3 (uses minigbm gralloc vs. gbm used on Pi 4) but I haven't really looked into this. android-rpi also uses a different gralloc which makes this interesting.

If you ask me, I'm of course more interested sorting any possible wifi issues on builds (if you are talking about https://github.com/lineage-rpi/android_kernel_brcm_rpi/issues/6 that's a place where you can contribute to that) than supporting camera on someone else's.
