### ISSUE TITLE
"Searching For Accessories"

### ISSUE THREAD

**Issue by mobrien118** [lineage-rpi/android_device_brcm_rpi4#7]
I hope this is the right place. I'm having an issue similar to https://github.com/lineage-rpi/android_kernel_brcm_rpi/issues/6, but I think it is different.

For me, the device keeps returning to "Searching for Accessories". I press F2 and it will drop to the LineageOS config screen for a random amount of time between 2 and 15 seconds. I can get through some of the config but then it returns back to "Searching for Accessories" and I have to start over.

Note: this is not rebooting but just restarting the UI, I think. Not sure how to troubleshoot or debug this.

**Comment by KonstaT** [comment]
What Pi 4 model are you using? What display resolution are you using? If you use a very large resolution you might run out of CMA memory allocation which is why the setup wizard crashes.

Impossible to say what the issue is exactly without seeing any logs. You would need to have a serial console adapter to gets logs  at this stage.

Possibly relevant discussion: http://disq.us/p/2ge2hlj
